Repository apache/cordova-electron, pull requests merged in 2019-07, with the labels that each got.

#85 fix: use spyOn for process global var
  tests/spec/unit/templates/cordova/lib/build.spec.js
  tests/spec/unit/templates/cordova/lib/clean.spec.js
  tests/spec/unit/templates/cordova/lib/run.spec.js
Labels: bug

#86 refactor: improve create test spec speed
  tests/spec/unit/create.spec.js
Labels: enhancement

#89 fix: prepare missing dependencies failure
  bin/templates/cordova/lib/PackageJsonParser.js
  tests/spec/unit/templates/cordova/lib/PackageJsonParser.spec.js
Labels: bug

#79 Filter icons only matching requirements
  bin/templates/cordova/lib/prepare.js
  tests/spec/unit/templates/cordova/lib/prepare.spec.js
Labels: bug, enhancement
